validação de msgs
victorcand/crud-laravel-project pull request #1
Opened 2021-04-19 18:14 UTC by victorcand

2021-04-20 01:34 UTC, jorgecandidoan requested changes

2021-04-20 01:34 UTC, jorgecandidoan commented on app/Http/Controllers/PizzaController.php
> +        $pizzas = PizzaRepository::validateIfHasPizzaInDatabase($request);
Isso deveria estar em um Service não um Repository

2021-04-20 01:34 UTC, jorgecandidoan commented on app/Http/Controllers/PizzaController.php
> +    public function store(PizzasFormRequest $request)
Por que criou um PizzasFormRequest???

2021-04-20 01:34 UTC, jorgecandidoan commented on app/Http/Controllers/PizzaController.php
> +        PizzaRepository::createPizza($request);
Deveria estar em um Service.

Dentro do Service tem que ter a validação

2021-04-20 01:34 UTC, jorgecandidoan commented on app/Http/Controllers/PizzaController.php
>          DB::table('pizzas')->where('id',$request->id)->delete();
Não é uma boa pratica ter um Db::table pegando os dados..

Isso deveria ser feito Pela Model e ser chamado por um Repository

2021-04-20 01:34 UTC, jorgecandidoan commented on app/Http/Requests/PizzasFormRequest.php
> +    public function authorize()
Faltou tipar o Retorno

2021-04-20 01:34 UTC, jorgecandidoan commented on app/Http/Controllers/PizzaController.php
>      public function index(Request $request)
Faltou tipar o retorno

2021-04-20 01:34 UTC, jorgecandidoan commented on app/Http/Controllers/PizzaController.php
> +    public function store(PizzasFormRequest $request)
Faltou tipar o retorno

2021-04-20 01:34 UTC, jorgecandidoan commented on app/Http/Requests/PizzasFormRequest.php
> +    public function rules()
Faltou tipar o retorno

2021-04-20 01:34 UTC, jorgecandidoan commented on app/Http/Requests/PizzasFormRequest.php
> +    public function messages()
Faltou tipar o retorno

2021-04-20 01:34 UTC, jorgecandidoan commented on app/Http/Requests/PizzasFormRequest.php
> +
Remover linha em branco

2021-04-20 01:34 UTC, jorgecandidoan commented on app/Http/Requests/PizzasFormRequest.php
> +
Remover linha em branco

2021-04-20 01:34 UTC, jorgecandidoan commented on app/Repositories/PizzaRepository.php
> +        $pizzas = DB::table('pizzas')->orderBy('id','desc')->get();
Esta errado utilizar o DB::table, teria que usar a Model e o Retorno não é uma Collection

2021-04-20 01:34 UTC, jorgecandidoan commented on app/Repositories/PizzaRepository.php
> +    public static function validateIfHasPizzaInDatabase($request): ?Collection
Este nome de Metodo esta muito estranho

2021-04-20 01:34 UTC, jorgecandidoan commented on app/Repositories/PizzaRepository.php
> +    public static function validateIfHasPizzaInDatabase($request): ?Collection
Tipar a variavel

2021-04-20 01:34 UTC, jorgecandidoan commented on app/Repositories/PizzaRepository.php
> +        if(count($pizzas) == 0){
Usar o empty para validar

2021-04-20 01:34 UTC, jorgecandidoan commented on app/Repositories/PizzaRepository.php
> +           $mensagemInfo = $request->session()->flash('mensagemInfo', 'Não há pizza cadastrada!');
Vai dar merda aqui... o Ideal seria colocar o flash e matar a execução e não deixar rolar..

2021-04-20 01:34 UTC, jorgecandidoan commented on app/Repositories/PizzaRepository.php
> +    public static function createPizza($request)
Tipar retorno e variavel

2021-04-20 01:34 UTC, jorgecandidoan commented on app/Repositories/PizzaRepository.php
> +        return $request->session()->flash('mensagem', 'Cadastro realizado com sucesso!');
Pular uma linha

2021-04-20 01:34 UTC, jorgecandidoan commented on app/Repositories/PizzaRepository.php
> +        return $request->session()->flash('mensagem', 'Cadastro realizado com sucesso!');
Não é trabalho do Repository colocar a mensagem do Flash.

2021-04-20 01:34 UTC, jorgecandidoan commented on app/Repositories/PizzaRepository.php
> +           $mensagemInfo = $request->session()->flash('mensagemInfo', 'Não há pizza cadastrada!');
Não é trabalho do Repository manipular a Flash message

2021-04-20 01:34 UTC, jorgecandidoan commented on app/Service/PizzaService.php
> +class PizzaService
Por que tem um service vazio?? e todas as regras estão na controller e no repository?

2021-04-20 01:34 UTC, jorgecandidoan commented on public/css/conteudo.css
>  }
Sempre pular uma linha no final do doc

2021-04-20 01:34 UTC, jorgecandidoan commented on resources/views/pizzaria/home.blade.php
> +                {{ $mensagemDelete }}
Esta estranho, pq a classe chamada SUCCESS tem o valoda da mensagemDelete?

Não programar igual o massacration.... ou usa PTbr ou usa Inglês

2021-04-20 01:34 UTC, jorgecandidoan commented on routes/web.php
>  Route::delete('/pizzaria/{id}',[PizzaController::class, 'destroy']);
Pular uma linha no final do Doc

2021-04-20 16:16 UTC, victorcand commented on app/Http/Controllers/PizzaController.php
> +    public function store(PizzasFormRequest $request)
PizzasFormRequest é para validação do form, alterei para PizzasRequest.

2021-04-27 03:01 UTC, jorgecandidoan requested changes

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Http/Controllers/PizzaController.php
>      public function index(Request $request)
Continua sem tipar o retorno

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Http/Controllers/PizzaController.php
remover linha em branco

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Http/Controllers/PizzaController.php
Remover linha em branco

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Http/Controllers/PizzaController.php
>      public function create(Request $request)
Faltou tipar o retorno

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Http/Controllers/PizzaController.php
> +    public function store(PizzaRequest $request)
Faltou tipar o retorno

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Http/Controllers/PizzaController.php
Remover linha em branco

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Http/Controllers/PizzaController.php
> +    public function edit(Request $request)
faltou tipar o retorno

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Http/Controllers/PizzaController.php
> +    public function edit(Request $request)
Normalmente utilizamos o nome Update.

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Http/Controllers/PizzaController.php
> +        $pizzas->editPizzaInDatabase($request);
editPizzaInDatabase este nome parece o nome de um metodo de Repositorio... e normalmente utilizamos UPDATE

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Http/Controllers/PizzaController.php
> +    public function search(Request $request)
Faltou tipar retorno

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Http/Controllers/PizzaController.php
>      public function destroy(Request $request)
Faltou tipar o retorno

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Http/Controllers/PizzaController.php
> +        $deletePizza->deletePizzaInListPizzas($request);
Este metodo deveria estar em um repository pq trata direto com o banco de dados, não precisa de um service para isso.

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Repositories/PizzaRepository.php
> +    public static function getListPizzasInDatabase(): ?Collection
Não precisa do nome InDatabase.. quando se trata de Repository subentendesse que é do banco de dados.

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Repositories/PizzaRepository.php
> +    public static function createPizza($request): ?Pizzas
eu não colocaria os nome.. createPizza eu colocaria direto o create, pq se é uma classe de Pizza.. ele só pode criar isso.. :D

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Repositories/PizzaRepository.php
> +    public static function deletePizza($request): void
Mesma coisa

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Repositories/PizzaRepository.php
> +        return;
se é void não precisa deste return vazio. pode deletar

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Repositories/PizzaRepository.php
> +        $pizza->where('id', $request->id)->delete();
tem jeito melhor de se fazer isso.

```suggestion
        Pizzas::query->where('id', $request->id)->delete();
```

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Repositories/PizzaRepository.php
> +    public static function editPizza($id, $newName, $newPrice, $newDescription): void
Mesma coisa. não precisa do Pizza no nome do metodo

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Repositories/PizzaRepository.php
> +    public static function editPizza($id, $newName, $newPrice, $newDescription): void
Tipar os parametros

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Repositories/PizzaRepository.php
> +        return;
Não precisa deste return

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Repositories/PizzaRepository.php
> +        $pizza = Pizzas::find($id);
o ideal seria um FindOrFail()

pq se não existir esta pizza com o id informado, você pode acabar criando registro que não existe.

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Repositories/PizzaRepository.php
> +        return Pizzas::where('pizza_name', 'like', '%' . $search . '%')
Pular uma  linha antes

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Repositories/PizzaRepository.php
> +            ->orWhere('pizza_price', 'like', '%' . $search . '%')
Cara se é preço pq vc esta usando um like?? preço é Numerico like é para achar fragmento de testo.. esta query esta horrivel e não vai performar bem

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Repositories/PizzaRepository.php
> +            ->orWhere('pizza_price', 'like', '%' . $search . '%')
usar like é para casos RAROS a perfomance dele é horrivel, ainda mais com 3 or com Like

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Service/PizzaService.php
> +        if (count($pizzas) == 0) {
o ideal seria dentro do Repository lançar uma exception caso não exista o registro e vc capturar aqui fora..

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Service/PizzaService.php
> +        return;
Deveria ter uma validação para ter certeza que foi criado.

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Service/PizzaService.php
> +        return;
Deveria ter uma validação para saber se foi realmente deletado

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Service/PizzaService.php
> +
Remover espaço em branco

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Service/PizzaService.php
> +    public function editPizzaInDatabase($request)
Tipar retorno e parametro

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Service/PizzaService.php
> +    public function deletePizzaInListPizzas($request): void
Tipar parametro

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Service/PizzaService.php
> +    public function createPizzaByForm($request): void
Tipar parametro

2021-04-27 03:01 UTC, jorgecandidoan commented on app/Service/PizzaService.php
> +    public function getListPizzas($request): ?Collection
Tipar parametro

2021-04-27 03:01 UTC, jorgecandidoan commented on public/css/all.css
> +@import "responsive.css";
Coloca uma linha no final do arquivo

2021-04-27 03:01 UTC, jorgecandidoan commented on public/css/responsive.css
> +}
Colocar uma linha no fim do arquivo

2021-04-27 03:01 UTC, jorgecandidoan commented on public/js/app.js
> +    const namePizzaEl = document.getElementById(`name-pizza-${pizzaId}`)
pq este nome? PizzaE1??

2021-04-27 03:01 UTC, jorgecandidoan commented on public/js/app.js
> +
remover espaço em branco

2021-04-27 03:01 UTC, jorgecandidoan commented on public/js/app.js
> +
remover espaço em branco

2021-04-27 03:01 UTC, jorgecandidoan commented on public/js/app.js
> +
remover espaço em branco

2021-04-27 03:01 UTC, jorgecandidoan commented on public/js/app.js
> +
remover espaço em branco

2021-04-27 03:01 UTC, jorgecandidoan commented on public/js/app.js
> +        //AQUI ESTÁ O PROBLEMA !!
Resolva o problema.. :D

2021-04-27 14:13 UTC, victorcand commented on app/Http/Controllers/PizzaController.php
> +        PizzaRepository::createPizza($request);
Foi alterado

2021-04-27 14:13 UTC, victorcand commented on app/Http/Controllers/PizzaController.php
>          DB::table('pizzas')->where('id',$request->id)->delete();
Foi alterado

2021-04-27 14:14 UTC, victorcand commented on app/Http/Requests/PizzasFormRequest.php
> +    public function authorize()
Foi excluido

2021-04-27 14:33 UTC, victorcand commented on app/Http/Requests/PizzasFormRequest.php
> +    public function rules()
retorno tipado!

2021-04-27 14:33 UTC, victorcand commented on app/Http/Requests/PizzasFormRequest.php
> +    public function messages()
retorno tipado!

2021-04-27 14:34 UTC, victorcand commented on app/Http/Requests/PizzasFormRequest.php
> +
Removido!

2021-04-27 14:34 UTC, victorcand commented on app/Repositories/PizzaRepository.php
> +        $pizzas = DB::table('pizzas')->orderBy('id','desc')->get();
Feito a alteração!

2021-04-27 14:35 UTC, victorcand commented on app/Repositories/PizzaRepository.php
> +    public static function validateIfHasPizzaInDatabase($request): ?Collection
Foi alterado!

2021-04-27 14:44 UTC, victorcand commented on app/Http/Requests/PizzasFormRequest.php
> +
Removido!

2021-04-27 14:44 UTC, victorcand commented on app/Repositories/PizzaRepository.php
> +    public static function validateIfHasPizzaInDatabase($request): ?Collection
O método foi removido.

2021-04-27 15:03 UTC, victorcand commented on app/Repositories/PizzaRepository.php
> +        if(count($pizzas) == 0){
Feito a alteração!

2021-04-27 15:08 UTC, victorcand commented on resources/views/pizzaria/home.blade.php
> +                {{ $mensagemDelete }}
Feito as alterações

2021-04-27 15:09 UTC, victorcand commented on routes/web.php
>  Route::delete('/pizzaria/{id}',[PizzaController::class, 'destroy']);
Feito a alteração

2021-04-27 15:10 UTC, victorcand commented on app/Repositories/PizzaRepository.php
> +    public static function createPizza($request)
Feito a alteração

2021-04-27 15:10 UTC, victorcand commented on app/Repositories/PizzaRepository.php
> +        return $request->session()->flash('mensagem', 'Cadastro realizado com sucesso!');
Feito a alteração.

2021-04-27 15:13 UTC, victorcand commented on app/Repositories/PizzaRepository.php
> +        return $request->session()->flash('mensagem', 'Cadastro realizado com sucesso!');
Feito a alteração.

2021-04-27 15:13 UTC, victorcand commented on app/Repositories/PizzaRepository.php
> +           $mensagemInfo = $request->session()->flash('mensagemInfo', 'Não há pizza cadastrada!');
Feito a alteração

2021-04-27 15:14 UTC, victorcand commented on app/Service/PizzaService.php
> +class PizzaService
Feito a implementação

2021-04-27 15:16 UTC, victorcand commented on public/css/conteudo.css
>  }
Feito a alteração

2021-04-27 15:17 UTC, victorcand commented on app/Http/Controllers/PizzaController.php
Feito a alteração

2021-04-27 15:18 UTC, victorcand commented on app/Http/Controllers/PizzaController.php
feito a alteração

2021-04-27 21:21 UTC, victorcand commented on app/Service/PizzaService.php
> +
Removido!

2021-04-29 13:48 UTC, merged